name: pybilt
channels:
  - defaults
  - conda-forge
dependencies:
  - griddataformats=0.4.0
  - gsd=1.5.3
  - mdanalysis=0.18.0
  - mdtraj=1.9.1
  - mmtf-python=1.1.2
  - tempdir=0.7.1
  - _license=1.1
  - alabaster=0.7.11
  - anaconda-client=1.7.2
  - anaconda=custom
  - anaconda-navigator=1.9.2
  - anaconda-project=0.8.2
  - appdirs=1.4.3
  - argcomplete=1.9.4
  - asn1crypto=0.24.0
  - astroid=1.6.5
  - astropy=2.0.2
  - atomicwrites=1.2.1
  - attrs=18.2.0
  - automat=0.7.0
  - babel=2.6.0
  - backports=1.0
  - backports.functools_lru_cache=1.5
  - backports.shutil_get_terminal_size=1.0.0
  - backports_abc=0.5
  - beautifulsoup4=4.6.3
  - biopython=1.69
  - bitarray=0.8.3
  - blas=1.0
  - blaze=0.10.1
  - bleach=2.1.4
  - bokeh=0.12.4
  - boto=2.49.0
  - bottleneck=1.2.1
  - bzip2=1.0.6
  - ca-certificates=2018.03.07
  - cairo=1.14.12
  - cdecimal=2.3
  - certifi=2018.8.24
  - cffi=1.11.5
  - cftime=1.0.0b1
  - chardet=3.0.4
  - chest=0.2.3
  - click=6.7
  - cloudpickle=0.5.6
  - clyent=1.2.2
  - colorama=0.3.9
  - configobj=5.0.6
  - configparser=3.5.0
  - constantly=15.1.0
  - contextlib2=0.5.5
  - cryptography=2.3.1
  - curl=7.61.0
  - cycler=0.10.0
  - cython=0.28.5
  - cytoolz=0.9.0.1
  - dask=0.13.0
  - datashape=0.5.4
  - dbus=1.13.2
  - decorator=4.3.0
  - defusedxml=0.5.0
  - dill=0.2.8.2
  - docutils=0.14
  - entrypoints=0.2.3
  - enum34=1.1.6
  - et_xmlfile=1.0.1
  - expat=2.2.6
  - fastcache=1.0.2
  - flask=1.0.2
  - flask-cors=3.0.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - funcsigs=1.0.2
  - functools32=3.2.3.2
  - futures=3.2.0
  - get_terminal_size=1.0.0
  - gevent=1.3.6
  - glib=2.56.2
  - gmp=6.1.2
  - gmpy2=2.0.8
  - graphite2=1.3.12
  - greenlet=0.4.15
  - grin=1.2.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.7.0
  - harfbuzz=1.8.8
  - hdf4=4.2.13
  - hdf5=1.10.2
  - heapdict=1.0.0
  - html5lib=1.0.1
  - hyperlink=18.0.0
  - icu=58.2
  - idna=2.7
  - imageio=2.2.0
  - imagesize=1.1.0
  - incremental=17.5.0
  - intel-openmp=2019.0
  - ipaddress=1.0.22
  - ipykernel=4.10.0
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.2
  - isort=4.3.4
  - itsdangerous=0.24
  - jbig=2.1
  - jdcal=1.4
  - jedi=0.12.1
  - jinja2=2.10
  - joblib=0.12.3
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kiwisolver=1.0.1
  - lazy-object-proxy=1.3.1
  - libcurl=7.61.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=8.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - libnetcdf=4.6.1
  - libpng=1.6.34
  - libsodium=1.0.16
  - libssh2=1.8.0
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.9
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.8
  - libxslt=1.1.32
  - llvmlite=0.24.0
  - locket=0.2.0
  - lxml=4.2.5
  - markupsafe=1.0
  - matplotlib=2.2.3
  - mccabe=0.6.1
  - mistune=0.8.3
  - mkl=2019.0
  - mkl-service=1.1.2
  - more-itertools=4.3.0
  - mpc=1.1.0
  - mpfr=4.0.1
  - mpmath=1.0.0
  - msgpack-python=0.5.6
  - multipledispatch=0.6.0
  - nbconvert=5.4.0
  - nbformat=4.4.0
  - ncurses=6.1
  - netcdf4=1.4.1
  - networkx=2.1
  - nltk=3.3.0
  - nose=1.3.7
  - notebook=5.6.0
  - numba=0.35.0
  - numexpr=2.6.2
  - numpy=1.13.3
  - numpydoc=0.8.0
  - odo=0.5.0
  - olefile=0.46
  - openpyxl=2.5.8
  - openssl=1.0.2p
  - packaging=17.1
  - pandas=0.20.3
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - parso=0.3.1
  - partd=0.3.8
  - path.py=11.1.0
  - pathlib2=2.3.2
  - patsy=0.4.1
  - pcre=8.42
  - pep8=1.7.1
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pillow=5.2.0
  - pip=10.0.1
  - pixman=0.34.0
  - pluggy=0.7.1
  - ply=3.11
  - prometheus_client=0.3.1
  - prompt_toolkit=1.0.15
  - psutil=5.4.7
  - ptyprocess=0.6.0
  - py=1.6.0
  - pyasn1=0.4.4
  - pyasn1-modules=0.2.2
  - pycairo=1.17.1
  - pycodestyle=2.4.0
  - pycosat=0.6.3
  - pycparser=2.18
  - pycrypto=2.6.1
  - pycurl=7.43.0.2
  - pyflakes=2.0.0
  - pygments=2.2.0
  - pylint=1.9.2
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - pysocks=1.6.8
  - pytables=3.4.2
  - pytest=3.8.1
  - python=2.7.15
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pywavelets=0.5.2
  - pyyaml=3.13
  - pyzmq=17.1.2
  - qt=5.9.6
  - qtawesome=0.5.0
  - qtconsole=4.4.1
  - qtpy=1.5.1
  - readline=7.0
  - redis=4.0.11
  - redis-py=2.10.6
  - requests=2.19.1
  - rope=0.11.0
  - ruamel_yaml=0.15.46
  - scandir=1.9.0
  - scikit-image=0.13.0
  - scikit-learn=0.19.0
  - scipy=0.19.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - service_identity=17.0.0
  - setuptools=40.2.0
  - simplegeneric=0.8.1
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.11.0
  - snowballstemmer=1.2.1
  - sockjs-tornado=1.0.5
  - sphinx=1.8.1
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.1.0
  - spyder=3.3.1
  - spyder-kernels=0.2.6
  - sqlalchemy=1.2.12
  - sqlite=3.25.2
  - ssl_match_hostname=3.5.0.1
  - statsmodels=0.8.0
  - subprocess32=3.5.2
  - sympy=1.3
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=5.1
  - traitlets=4.3.2
  - twisted=18.7.0
  - typing=3.6.6
  - unicodecsv=0.14.1
  - urllib3=1.23
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.14.1
  - wheel=0.31.1
  - widgetsnbextension=3.4.2
  - wrapt=1.10.11
  - xlrd=1.1.0
  - xlsxwriter=1.1.0
  - xlwt=1.3.0
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.2.5
  - zlib=1.2.11
  - zope=1.0
  - zope.interface=4.5.0
  - pip:
    - backports.ssl-match-hostname==3.5.0.1
    - commonmark==0.5.4
    - future==0.16.0
    - msgpack==0.5.6
    - recommonmark==0.4.0
    - sphinx-rtd-theme==0.2.4
    - tables==3.4.2
