name: pybilt
channels:
  - defaults
  - conda-forge
dependencies:
  - ca-certificates=2018.8.24
  - cftime=1.0.1
  - griddataformats=0.4.0
  - gsd=1.5.3
  - joblib=0.12.5
  - krb5=1.14.6
  - mdanalysis=0.18.0
  - mmtf-python=1.1.2
  - networkx=2.2
  - alabaster=0.7.11
  - asn1crypto=0.24.0
  - babel=2.6.0
  - backports=1.0
  - backports.functools_lru_cache=1.5
  - backports_abc=0.5
  - biopython=1.72
  - blas=1.0
  - bzip2=1.0.6
  - certifi=2018.8.24
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.3.1
  - curl=7.61.0
  - cycler=0.10.0
  - cython=0.28.5
  - dbus=1.13.2
  - decorator=4.3.0
  - docutils=0.14
  - enum34=1.1.6
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - funcsigs=1.0.2
  - functools32=3.2.3.2
  - future=0.16.0
  - futures=3.2.0
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf4=4.2.13
  - hdf5=1.10.2
  - icu=58.2
  - idna=2.7
  - imagesize=1.1.0
  - intel-openmp=2019.0
  - ipaddress=1.0.22
  - jinja2=2.10
  - jpeg=9b
  - kiwisolver=1.0.1
  - libcurl=7.61.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.34
  - libssh2=1.8.0
  - libstdcxx-ng=8.2.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.8
  - markupsafe=1.0
  - matplotlib=2.2.3
  - mkl=2019.0
  - mkl_fft=1.0.4
  - mkl_random=1.0.1
  - mock=2.0.0
  - msgpack-python=0.5.6
  - ncurses=6.1
  - netcdf4=1.4.1
  - numpy=1.15.1
  - numpy-base=1.15.1
  - openssl=1.0.2p
  - packaging=17.1
  - pandas=0.23.4
  - patsy=0.5.0
  - pbr=4.2.0
  - pcre=8.42
  - pip=10.0.1
  - pycparser=2.18
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - pysocks=1.6.8
  - python=2.7.15
  - python-dateutil=2.7.3
  - pytz=2018.5
  - qt=5.9.6
  - readline=7.0
  - requests=2.19.1
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - seaborn=0.9.0
  - setuptools=40.2.0
  - singledispatch=3.4.0.3
  - sip=4.19.8
  - six=1.11.0
  - snowballstemmer=1.2.1
  - sphinx=1.8.1
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.1.0
  - sqlite=3.24.0
  - statsmodels=0.9.0
  - subprocess32=3.5.2
  - tk=8.6.8
  - tornado=5.1
  - typing=3.6.6
  - urllib3=1.23
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - commonmark==0.5.4
    - msgpack==0.5.6
    - recommonmark==0.4.0
    - sphinx-rtd-theme==0.4.1
