name: pybilt
channels:
  - defaults
  - conda-forge
dependencies:
  - alabaster=0.7.12
  - asn1crypto=0.24.0
  - babel=2.6.0
  - blas=1.0
  - ca-certificates=2019.1.23
  - certifi=2018.11.29
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.5
  - cycler=0.10.0
  - dbus=1.13.6
  - docutils=0.14
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - future=0.17.1
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.8
  - imagesize=1.1.0
  - intel-openmp=2019.1
  - jinja2=2.10
  - jpeg=9b
  - kiwisolver=1.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.36
  - libstdcxx-ng=8.2.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.0
  - matplotlib=3.0.2
  - mkl=2019.1
  - mkl_fft=1.0.10
  - mkl_random=1.0.2
  - ncurses=6.1
  - numpy=1.15.4
  - numpy-base=1.15.4
  - openssl=1.1.1a
  - packaging=19.0
  - pandas=0.24.1
  - patsy=0.5.1
  - pcre=8.42
  - pip=19.0.1
  - pycparser=2.19
  - pygments=2.3.1
  - pyopenssl=19.0.0
  - pyparsing=2.3.1
  - pyqt=5.9.2
  - pysocks=1.6.8
  - python=3.6.8
  - python-dateutil=2.7.5
  - pytz=2018.9
  - qt=5.9.7
  - readline=7.0
  - requests=2.21.0
  - scipy=1.2.1
  - seaborn=0.9.0
  - setuptools=40.8.0
  - sip=4.19.8
  - six=1.12.0
  - snowballstemmer=1.2.1
  - sphinx=1.8.4
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.1.0
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - tk=8.6.8
  - tornado=5.1.1
  - urllib3=1.24.1
  - wheel=0.32.3
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - commonmark==0.8.1
    - recommonmark==0.5.0
    - sphinx-rtd-theme==0.4.3

