name: pybilt_27_rtd
channels:
  - defaults
  - conda-forge
dependencies:
  - biopython=1.72
  - ca-certificates=2018.8.24
  - certifi=2018.8.24
  - cftime=1.0.1
  - curl=7.61.0
  - decorator=4.3.0
  - griddataformats=0.4.0
  - gsd=1.5.3
  - hdf4=4.2.13
  - hdf5=1.10.2
  - joblib=0.12.5
  - krb5=1.14.6
  - libgfortran=3.0.0
  - libnetcdf=4.6.1
  - libssh2=1.8.0
  - mdanalysis=0.18.0
  - mmtf-python=1.1.2
  - msgpack-python=0.5.6
  - netcdf4=1.4.1
  - networkx=2.2
  - openssl=1.0.2p
  - backports=1.0
  - backports.functools_lru_cache=1.5
  - backports_abc=0.5
  - blas=1.0
  - cycler=0.10.0
  - dbus=1.13.2
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - functools32=3.2.3.2
  - future=0.16.0
  - futures=3.2.0
  - glib=2.56.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2019.0
  - jpeg=9b
  - kiwisolver=1.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.34
  - libstdcxx-ng=8.2.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.8
  - matplotlib=2.2.3
  - mkl=2019.0
  - mkl_fft=1.0.4
  - mkl_random=1.0.1
  - ncurses=6.1
  - numpy=1.15.1
  - numpy-base=1.15.1
  - pandas=0.23.4
  - patsy=0.5.0
  - pcre=8.42
  - pip=10.0.1
  - pyparsing=2.2.0
  - pyqt=5.9.2
  - python=2.7.15
  - python-dateutil=2.7.3
  - pytz=2018.5
  - qt=5.9.6
  - readline=7.0
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - seaborn=0.9.0
  - setuptools=40.2.0
  - singledispatch=3.4.0.3
  - sip=4.19.12
  - six=1.11.0
  - sqlite=3.24.0
  - statsmodels=0.9.0
  - subprocess32=3.5.2
  - tk=8.6.8
  - tornado=5.1
  - wheel=0.31.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - msgpack==0.5.6
